const CurrentNotebookConstants = {
  RECEIVE_ALL_NOTES: "RECEIVE_ALL_NOTES",
  RECEIVE_NOTE: "RECEIVE_NOTE",
  REMOVE_NOTE: "REMOVE_NOTE",
  UPDATE_NOTEBOOK_NOTES: "UPDATE_NOTEBOOK_NOTES",
  RECEIVE_NOTE_NEW_NOTEBOOK: "RECEIVE_NOTE_NEW_NOTEBOOK"
};

module.exports = CurrentNotebookConstants;
