const NotebookConstants = {
  GET_ALL_NOTEBOOKS: "GET_ALL_NOTEBOOKS",
  REMOVE_NOTEBOOK: "REMOVE_NOTEBOOK",
  RECEIVE_NOTEBOOK: "RECEIVE_NOTEBOOK",
  RECEIVE_UPDATED_NOTEBOOK: "RECEIVE_UPDATED_NOTEBOOK"
};

module.exports = NotebookConstants;
