const TagConstants = {
  RECEIVE_TAG: "RECEIVE_TAG",
  RECEIVE_ALL_TAGS: "RECEIVE_ALL_TAGS",
  RECEIVE_CURRENT_TAG: "RECEIVE_CURRENT_TAG",
  REMOVE_TAG: "REMOVE_TAG",
  UPDATE_NOTE_AND_TAG: "UPDATE_NOTE_AND_TAG"
};

module.exports = TagConstants;
